/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.gva.edu.iesjuandegaray.bicis.valenbiciapiv2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sanfe
 */
public class ConexionBDD extends javax.swing.JFrame {
    
    private static Connection con;
    private static Statement s;
    protected static DatosJSon dJSon;
    private static int numEst = 3;

    private static final String driver = "com.mysql.jdbc.Driver";
    private static final String user = "admin";
    private static final String pass = "Patata-9&Ceboia";
    private static final String url = "jdbc:mysql://databasedmp.c32z3apotslk.us-east-1.rds.amazonaws.com/valenbicidb?";
    
    /**
     * Creates new form ConexionBDD
     */
    public ConexionBDD() {
        initComponents();
        dJSon = new DatosJSon(numEst);
        jTxtInpNum.setText(""+numEst); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtInpNum = new javax.swing.JTextField();
        jBtnDatos = new javax.swing.JButton();
        jBtnConectar = new javax.swing.JButton();
        jBtnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLblDatos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLblEstado = new javax.swing.JLabel();
        jLblAdd = new javax.swing.JLabel();
        jBtnDesconectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduce el número de estaciones a consultar: ");

        jTxtInpNum.setText("Num Estaciones");
        jTxtInpNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtInpNumFocusLost(evt);
            }
        });

        jBtnDatos.setText("Datos");
        jBtnDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDatosMouseClicked(evt);
            }
        });

        jBtnConectar.setText("Conectar");
        jBtnConectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnConectarMouseClicked(evt);
            }
        });

        jBtnAdd.setText("Añadir a BDD");
        jBtnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAddMouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLblDatos.setText("Obtener Datos de Estaciones");

        jLabel2.setText("Estado Conexión: ");

        jLblEstado.setText("Desconectado");

        jLblAdd.setText("Primero Obtener Datos de estaciones y Conectar con BDD");

        jBtnDesconectar.setText("Cerrar conexión");
        jBtnDesconectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDesconectarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtInpNum, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jBtnDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnConectar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblDatos)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLblEstado))
                            .addComponent(jLblAdd)
                            .addComponent(jBtnDesconectar))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxtInpNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnDatos)
                    .addComponent(jLblDatos))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConectar)
                    .addComponent(jLabel2)
                    .addComponent(jLblEstado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAdd)
                    .addComponent(jLblAdd))
                .addGap(18, 18, 18)
                .addComponent(jBtnDesconectar)
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnConectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnConectarMouseClicked
        // TODO add your handling code here:
        conector();
        jBtnAdd.setEnabled(true);
    }//GEN-LAST:event_jBtnConectarMouseClicked

    private void jBtnDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDatosMouseClicked
        // TODO add your handling code here:
        dJSon.mostrarDatos(numEst);
        jLblDatos.setText("Datos de estaciones:");
        jTextArea1.setText(dJSon.getDatos());
    }//GEN-LAST:event_jBtnDatosMouseClicked

    private void jBtnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAddMouseClicked
        // TODO add your handling code here:
        try{      
            String[] values = dJSon.getValues();
            String estacionId = "";
            String direccion = "";
            String bicisDisponibles = "";
            String anclajesLibres = "";
            String estadoOperativo = "";
            String longitud = "";
            String latitud = "";
            s = con.createStatement();
            
            for(int i = 0; i< values.length; i++){
                String[] estacion = values[i].split("%");
                estacionId = estacion[0];
                direccion = estacion[1];
                bicisDisponibles = estacion[2];
                anclajesLibres = estacion[3];
                estadoOperativo = "T".equals(estacion[4])? "1":"0";
                longitud = estacion[5];
                latitud = estacion[6];
                String query = "INSERT INTO historico(estacion_id, direccion," + 
                    " bicis_disponibles, anclajes_libres, estado_operativo, fecha_registro, ubicacion) " +
                    "VALUES('"+estacionId+"','"+direccion+"','"+bicisDisponibles+"'," +
                        "'"+anclajesLibres+"','"+estadoOperativo+"', CURRENT_TIMESTAMP, POINT(" + latitud + "," + longitud + "));";
                
                s.execute(query);        
                
            }         
            
            s.close();
        }         
        // Si la conexion NO fue exitosa mostramos un mensaje de error         
        catch (SQLException e) {
            jLblAdd.setText("Error de conexion" + e);
        }
    }//GEN-LAST:event_jBtnAddMouseClicked

    private void jBtnDesconectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDesconectarMouseClicked
        // TODO add your handling code here:
        try {             
            // TODO Añade aquí el código para cerrar la conexión con la Base de Datos               
            con.close();            
            jLblEstado.setText("Desconectado");
        } catch (SQLException ex) {
            Logger.getLogger(ConexionBDD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnDesconectarMouseClicked

    private void jTxtInpNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtInpNumFocusLost
        // TODO add your handling code here:
        numEst = Integer.parseInt(jTxtInpNum.getText());
        dJSon.mostrarDatos(numEst);
        jLblDatos.setText("Datos estaciones:");
        jTextArea1.setText(dJSon.getDatos());
    }//GEN-LAST:event_jTxtInpNumFocusLost

    public void conector() {
        try {
            // Añade aquí el código para establecer la conexión con la base de datos
            Class.forName(driver);
            con = DriverManager.getConnection(url,user,pass); 
            System.out.println("Conexión Establecida");
            jLblEstado.setText("Conectado");
        }catch (SQLException e) {
            System.out.println("SQL Exception: "+ e.toString());
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(ConexionBDD.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConexionBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConexionBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConexionBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConexionBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConexionBDD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnConectar;
    private javax.swing.JButton jBtnDatos;
    private javax.swing.JButton jBtnDesconectar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblAdd;
    private javax.swing.JLabel jLblDatos;
    private javax.swing.JLabel jLblEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTxtInpNum;
    // End of variables declaration//GEN-END:variables
}
